/**
 *  MIT No Attribution
 *
 *  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 *
 *  Permission is hereby granted, free of charge, to any person obtaining a copy of
 *  the Software without restriction, including without limitation the rights to
 *  use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
 *  the Software, and to permit persons to whom the Software is furnished to do so.
 *
 *  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 *  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 *  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 *  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 *  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 *  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 *  SOFTWARE.
 */

import * as path from 'path';
import { Duration } from 'aws-cdk-lib';
import * as dynamodb from 'aws-cdk-lib/aws-dynamodb';
import * as events from 'aws-cdk-lib/aws-events';
import * as targets from 'aws-cdk-lib/aws-events-targets';
import { Runtime, Architecture } from 'aws-cdk-lib/aws-lambda';
import * as lambda from 'aws-cdk-lib/aws-lambda-nodejs';
import { NagSuppressions } from 'cdk-nag';
import { Construct } from 'constructs';
import { TaskTable } from './task-table';

/** Sweep Lambda timeout (minutes) — bounded reply edits, well under a sweep interval. */
const SWEEP_TIMEOUT_MINUTES = 2;

/** Default heartbeat sweep interval (minutes). Short enough that a long run shows liveness quickly. */
const DEFAULT_SCHEDULE_MINUTES = 2;

/** Sweep Lambda memory (MB). */
const SWEEP_MEMORY_MB = 256;

/** Properties for the IterationHeartbeat construct. */
export interface IterationHeartbeatProps {
  /** TaskTable (has the StatusIndex GSI the sweep queries for RUNNING tasks). */
  readonly taskTable: dynamodb.ITable;
  /**
   * How often to sweep RUNNING iterations and refresh their maturing reply.
   * @default Duration.minutes(2)
   */
  readonly schedule?: Duration;
}

/**
 * K6 — mid-run liveness heartbeat (scheduled).
 *
 * A scheduled Lambda that finds RUNNING comment-triggered iteration tasks and
 * EDITS the existing maturing Linear reply in place to show liveness ("🔄
 * Working — updating PR #N… _8m elapsed_"), so a long run isn't a silent black
 * box between 👀 and the terminal ✅/❌ (live-caught ABCA-483: 22-min silence).
 *
 * The construct owns only the Lambda + schedule + TaskTable read. The Linear
 * workspace-registry env + per-workspace OAuth ``GetSecretValue`` grant are
 * wired by the stack after instantiation (mirrors OrchestrationReconciler),
 * since they belong to the LinearIntegration construct.
 */
export class IterationHeartbeat extends Construct {
  public readonly fn: lambda.NodejsFunction;

  constructor(scope: Construct, id: string, props: IterationHeartbeatProps) {
    super(scope, id);

    const handlersDir = path.join(__dirname, '..', 'handlers');

    this.fn = new lambda.NodejsFunction(this, 'SweepFn', {
      entry: path.join(handlersDir, 'iteration-heartbeat-sweep.ts'),
      handler: 'handler',
      runtime: Runtime.NODEJS_24_X,
      architecture: Architecture.ARM_64,
      timeout: Duration.minutes(SWEEP_TIMEOUT_MINUTES),
      memorySize: SWEEP_MEMORY_MB,
      environment: {
        TASK_TABLE_NAME: props.taskTable.tableName,
        TASK_STATUS_INDEX_NAME: TaskTable.STATUS_INDEX,
      },
      bundling: {
        externalModules: ['@aws-sdk/*'],
      },
    });

    // Read-only on the TaskTable (StatusIndex query). No write — a heartbeat
    // never mutates task state; it only edits a Linear comment.
    props.taskTable.grantReadData(this.fn);

    const schedule = props.schedule ?? Duration.minutes(DEFAULT_SCHEDULE_MINUTES);
    const rule = new events.Rule(this, 'HeartbeatSchedule', {
      schedule: events.Schedule.rate(schedule),
    });
    rule.addTarget(new targets.LambdaFunction(this.fn));

    NagSuppressions.addResourceSuppressions(this.fn, [
      {
        id: 'AwsSolutions-IAM4',
        reason: 'AWSLambdaBasicExecutionRole is required for CloudWatch Logs access',
      },
      {
        id: 'AwsSolutions-IAM5',
        reason: 'DynamoDB index/* wildcard generated by CDK grantReadData; '
          + 'per-workspace linear-oauth secret prefix grant added by the stack',
      },
    ], true);
  }
}
