/**
 *  MIT No Attribution
 *
 *  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 *
 *  Permission is hereby granted, free of charge, to any person obtaining a copy of
 *  the Software without restriction, including without limitation the rights to
 *  use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
 *  the Software, and to permit persons to whom the Software is furnished to do so.
 *
 *  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 *  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 *  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 *  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 *  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 *  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 *  SOFTWARE.
 */

import { RemovalPolicy } from 'aws-cdk-lib';
import * as dynamodb from 'aws-cdk-lib/aws-dynamodb';
import { Construct } from 'constructs';

/**
 * Properties for SlackChannelMappingTable construct.
 */
export interface SlackChannelMappingTableProps {
  /**
   * Optional table name override.
   * @default - auto-generated by CloudFormation
   */
  readonly tableName?: string;

  /**
   * Removal policy for the table.
   * @default RemovalPolicy.DESTROY
   */
  readonly removalPolicy?: RemovalPolicy;

  /**
   * Whether to enable point-in-time recovery.
   * @default true
   */
  readonly pointInTimeRecovery?: boolean;
}

/**
 * DynamoDB table mapping Slack channels to a default GitHub repository.
 *
 * The Slack analogue of {@link LinearProjectMappingTable}: it lets a workspace
 * admin onboard a channel so members no longer have to type `owner/repo` in
 * every `@mention` — a bare mention in the channel routes to the mapped repo.
 *
 * Schema: channel_id (PK) — composite key `{team_id}#{channel_id}`.
 * The composite key keeps a single equality-queryable partition key while
 * staying globally unique across workspaces (a Slack channel id can repeat
 * across teams).
 *
 * Fields:
 * - repo — `owner/repo` the channel defaults to
 * - default_label — optional task label filter (reserved for future use)
 * - status — 'active' | 'removed'
 * - onboarded_at, updated_at — ISO timestamps
 *
 * The table is schemaless apart from the partition key; new fields are additive
 * and read with defaults, so existing rows need no migration.
 */
export class SlackChannelMappingTable extends Construct {
  /**
   * The underlying DynamoDB table.
   */
  public readonly table: dynamodb.Table;

  constructor(scope: Construct, id: string, props: SlackChannelMappingTableProps = {}) {
    super(scope, id);

    this.table = new dynamodb.Table(this, 'Table', {
      tableName: props.tableName,
      partitionKey: {
        name: 'channel_id',
        type: dynamodb.AttributeType.STRING,
      },
      billingMode: dynamodb.BillingMode.PAY_PER_REQUEST,
      pointInTimeRecoverySpecification: {
        pointInTimeRecoveryEnabled: props.pointInTimeRecovery ?? true,
      },
      removalPolicy: props.removalPolicy ?? RemovalPolicy.DESTROY,
    });
  }
}
