/**
 *  MIT No Attribution
 *
 *  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 *
 *  Permission is hereby granted, free of charge, to any person obtaining a copy of
 *  the Software without restriction, including without limitation the rights to
 *  use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
 *  the Software, and to permit persons to whom the Software is furnished to do so.
 *
 *  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 *  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 *  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 *  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 *  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 *  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 *  SOFTWARE.
 */

import * as path from 'path';
import { Duration } from 'aws-cdk-lib';
import * as dynamodb from 'aws-cdk-lib/aws-dynamodb';
import * as events from 'aws-cdk-lib/aws-events';
import * as targets from 'aws-cdk-lib/aws-events-targets';
import { Architecture, Runtime } from 'aws-cdk-lib/aws-lambda';
import * as lambda from 'aws-cdk-lib/aws-lambda-nodejs';
import { NagSuppressions } from 'cdk-nag';
import { Construct } from 'constructs';

/**
 * Properties for StrandedOrchestrationReconciler construct.
 */
export interface StrandedOrchestrationReconcilerProps {
  /** OrchestrationTable — read DAG state, write recovered child statuses. */
  readonly orchestrationTable: dynamodb.ITable;
  /** TaskTable — read released children's task status (terminal? built?) + createTaskCore writes. */
  readonly taskTable: dynamodb.ITable;
  /** TaskEventsTable — createTaskCore writes task_created events. */
  readonly taskEventsTable: dynamodb.ITable;
  /** Orchestrator function ARN — releaseChild → createTaskCore async-invokes it. */
  readonly orchestratorFunctionArn?: string;
  /**
   * Sweep cadence. Long enough to amortise the scan; short enough to
   * clear a lost-event stall in a reasonable user-facing time.
   * @default Duration.minutes(10)
   */
  readonly schedule?: Duration;
}

/**
 * Scheduled backstop for Linear orchestration (#247, gap #303).
 *
 * The live ``OrchestrationReconciler`` reacts to TaskTable-stream terminal
 * events to release dependency-unblocked children. If it is unavailable
 * when an event fires (deploy/throttle/OOM/DLQ-parked record) that event
 * is lost and the orchestration stalls. This scheduled sweep re-derives
 * gating truth from persisted state and recovers stranded children
 * (see ``handlers/reconcile-stranded-orchestrations.ts``).
 *
 * Mirrors ``StrandedTaskReconciler``. Grants match the live reconciler
 * because it runs the same ``createTaskCore`` release path in-process.
 */

/** Sweep Lambda timeout (minutes) — matches the live reconciler's createTaskCore
 *  + Bedrock/S3 SDK bundle cold-start + release work. */
const SWEEP_TIMEOUT_MINUTES = 5;

export class StrandedOrchestrationReconciler extends Construct {
  public readonly fn: lambda.NodejsFunction;

  constructor(scope: Construct, id: string, props: StrandedOrchestrationReconcilerProps) {
    super(scope, id);

    const handlersDir = path.join(__dirname, '..', 'handlers');

    this.fn = new lambda.NodejsFunction(this, 'ReconcilerFn', {
      entry: path.join(handlersDir, 'reconcile-stranded-orchestrations.ts'),
      handler: 'handler',
      runtime: Runtime.NODEJS_24_X,
      architecture: Architecture.ARM_64,
      timeout: Duration.minutes(SWEEP_TIMEOUT_MINUTES),
      // 512 MB to match the live reconciler — same createTaskCore +
      // Bedrock/S3 SDK bundle (see OrchestrationReconciler memory note).
      memorySize: 512,
      environment: {
        ORCHESTRATION_TABLE_NAME: props.orchestrationTable.tableName,
        TASK_TABLE_NAME: props.taskTable.tableName,
        TASK_EVENTS_TABLE_NAME: props.taskEventsTable.tableName,
        ...(props.orchestratorFunctionArn && {
          ORCHESTRATOR_FUNCTION_ARN: props.orchestratorFunctionArn,
        }),
      },
      bundling: {
        externalModules: ['@aws-sdk/*'],
      },
    });

    props.orchestrationTable.grantReadWriteData(this.fn);
    props.taskTable.grantReadWriteData(this.fn);
    props.taskEventsTable.grantReadWriteData(this.fn);

    const schedule = props.schedule ?? Duration.minutes(10);
    const rule = new events.Rule(this, 'SweepSchedule', {
      schedule: events.Schedule.rate(schedule),
    });
    rule.addTarget(new targets.LambdaFunction(this.fn));

    NagSuppressions.addResourceSuppressions(this.fn, [
      {
        id: 'AwsSolutions-IAM4',
        reason: 'AWSLambdaBasicExecutionRole is required for CloudWatch Logs access',
      },
      {
        id: 'AwsSolutions-IAM5',
        reason:
          'DynamoDB index/* wildcards generated by CDK grantReadWriteData for the '
          + 'orchestration scan + child-task lookups + createTaskCore write path',
      },
    ], true);
  }
}
