/**
 *  MIT No Attribution
 *
 *  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 *
 *  Permission is hereby granted, free of charge, to any person obtaining a copy of
 *  the Software without restriction, including without limitation the rights to
 *  use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
 *  the Software, and to permit persons to whom the Software is furnished to do so.
 *
 *  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 *  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 *  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 *  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 *  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 *  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 *  SOFTWARE.
 */

import { RemovalPolicy } from 'aws-cdk-lib';
import * as dynamodb from 'aws-cdk-lib/aws-dynamodb';
import { Construct } from 'constructs';

/**
 * Properties for TaskTable construct.
 */
export interface TaskTableProps {
  /**
   * Optional table name override.
   * @default - auto-generated by CloudFormation
   */
  readonly tableName?: string;

  /**
   * Removal policy for the table.
   * @default RemovalPolicy.DESTROY
   */
  readonly removalPolicy?: RemovalPolicy;

  /**
   * Whether to enable point-in-time recovery.
   * @default true
   */
  readonly pointInTimeRecovery?: boolean;
}

/**
 * DynamoDB table for persisting task state across the agent lifecycle.
 *
 * Schema: task_id (PK) with three GSIs for querying by user+status,
 * by status (queue processing), and by idempotency key (dedup).
 *
 * GSIs:
 * - UserStatusIndex (PK: user_id, SK: status_created_at) — "my tasks" queries
 * - StatusIndex (PK: status, SK: created_at) — queue processing, monitoring
 * - IdempotencyIndex (PK: idempotency_key) — sparse index for dedup
 * - LinearIssueIndex (PK: linear_issue_id, SK: created_at) — sparse; resolve a
 *   Linear issue back to its newest ABCA task + PR (#247 UX.3 standalone
 *   comment trigger)
 */
export class TaskTable extends Construct {
  /**
   * GSI name for querying tasks by user and status.
   * PK: user_id, SK: status_created_at (composite: `{status}#{created_at}`).
   */
  public static readonly USER_STATUS_INDEX = 'UserStatusIndex';

  /**
   * GSI name for querying tasks by status.
   * PK: status, SK: created_at.
   */
  public static readonly STATUS_INDEX = 'StatusIndex';

  /**
   * GSI name for idempotency dedup.
   * PK: idempotency_key. Sparse index — only items with the key are projected.
   */
  public static readonly IDEMPOTENCY_INDEX = 'IdempotencyIndex';

  /**
   * GSI name for resolving a Linear issue → its newest ABCA task + PR (#247
   * UX.3). PK: linear_issue_id, SK: created_at (newest task wins). Sparse —
   * only Linear-origin tasks (which write the top-level ``linear_issue_id``
   * attribute) are projected; GitHub/Slack/API tasks are absent. Powers the
   * standalone ``@bgagent`` comment trigger on a plain (non-orchestration)
   * issue, where no orchestration row records the issue→PR link.
   */
  public static readonly LINEAR_ISSUE_INDEX = 'LinearIssueIndex';

  /**
   * The underlying DynamoDB table. Use this to grant access or read the table name.
   */
  public readonly table: dynamodb.Table;

  constructor(scope: Construct, id: string, props: TaskTableProps = {}) {
    super(scope, id);

    this.table = new dynamodb.Table(this, 'Table', {
      tableName: props.tableName,
      partitionKey: {
        name: 'task_id',
        type: dynamodb.AttributeType.STRING,
      },
      billingMode: dynamodb.BillingMode.PAY_PER_REQUEST,
      timeToLiveAttribute: 'ttl',
      pointInTimeRecoverySpecification: {
        pointInTimeRecoveryEnabled: props.pointInTimeRecovery ?? true,
      },
      // NEW_IMAGE stream feeds the #247 orchestration reconciler
      // (`OrchestrationReconciler`), which reacts to child tasks reaching
      // terminal status to release dependency-unblocked children. This is
      // the table's FIRST and only stream consumer — deliberately on
      // TaskTable rather than TaskEventsTable, whose stream is already at
      // its 2-consumer limit (FanOutConsumer + ApprovalMetricsPublisher;
      // see TaskEventsTable). NEW_IMAGE suffices — the reconciler reads
      // status/build_passed/orchestration_id off the new record image.
      // Enabling a stream on an existing table is an in-place CFN update
      // (no table replacement).
      stream: dynamodb.StreamViewType.NEW_IMAGE,
      removalPolicy: props.removalPolicy ?? RemovalPolicy.DESTROY,
    });

    // GSI: query tasks by user, optionally filtered by status
    this.table.addGlobalSecondaryIndex({
      indexName: TaskTable.USER_STATUS_INDEX,
      partitionKey: { name: 'user_id', type: dynamodb.AttributeType.STRING },
      sortKey: { name: 'status_created_at', type: dynamodb.AttributeType.STRING },
      projectionType: dynamodb.ProjectionType.ALL,
    });

    // GSI: query tasks by status (for queue processing, monitoring)
    this.table.addGlobalSecondaryIndex({
      indexName: TaskTable.STATUS_INDEX,
      partitionKey: { name: 'status', type: dynamodb.AttributeType.STRING },
      sortKey: { name: 'created_at', type: dynamodb.AttributeType.STRING },
      projectionType: dynamodb.ProjectionType.ALL,
    });

    // GSI: idempotency dedup (sparse — only items with idempotency_key)
    this.table.addGlobalSecondaryIndex({
      indexName: TaskTable.IDEMPOTENCY_INDEX,
      partitionKey: { name: 'idempotency_key', type: dynamodb.AttributeType.STRING },
      projectionType: dynamodb.ProjectionType.KEYS_ONLY,
    });

    // GSI: Linear issue → newest ABCA task + PR (sparse — only Linear-origin
    // tasks carry the top-level linear_issue_id). #247 UX.3 standalone
    // comment trigger. INCLUDE-projects just the fields the trigger reads, so
    // the index stays lean (no full-item copy on every task write).
    this.table.addGlobalSecondaryIndex({
      indexName: TaskTable.LINEAR_ISSUE_INDEX,
      partitionKey: { name: 'linear_issue_id', type: dynamodb.AttributeType.STRING },
      sortKey: { name: 'created_at', type: dynamodb.AttributeType.STRING },
      projectionType: dynamodb.ProjectionType.INCLUDE,
      // iteration-UX: cost_usd + screenshot_url + code_changed/answer_text added so
      // the maturing iteration reply can sum a running cost total across rounds and
      // fold in the preview/answer without a per-task GetItem fan-out.
      nonKeyAttributes: [
        'pr_url', 'pr_number', 'status', 'repo', 'user_id', 'channel_metadata',
        'cost_usd', 'screenshot_url', 'code_changed', 'answer_text',
      ],
    });
  }
}
