/**
 *  MIT No Attribution
 *
 *  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 *
 *  Permission is hereby granted, free of charge, to any person obtaining a copy of
 *  the Software without restriction, including without limitation the rights to
 *  use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
 *  the Software, and to permit persons to whom the Software is furnished to do so.
 *
 *  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 *  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 *  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 *  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 *  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 *  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 *  SOFTWARE.
 */

import { RemovalPolicy } from 'aws-cdk-lib';
import * as dynamodb from 'aws-cdk-lib/aws-dynamodb';
import { Construct } from 'constructs';

/**
 * Properties for TaskNudgesTable construct.
 */
export interface TaskNudgesTableProps {
  /**
   * Optional table name override.
   * @default - auto-generated by CloudFormation
   */
  readonly tableName?: string;

  /**
   * Removal policy for the table.
   * @default RemovalPolicy.DESTROY
   */
  readonly removalPolicy?: RemovalPolicy;

  /**
   * Whether to enable point-in-time recovery.
   * @default true
   */
  readonly pointInTimeRecovery?: boolean;
}

/**
 * DynamoDB table for Phase 2 nudge messages.
 *
 * Schema: task_id (PK) + nudge_id (SK, ULID).
 *
 * Nudges are short steering messages from a user to a running agent,
 * submitted via `POST /v1/tasks/{task_id}/nudge`. They are persisted
 * here after guardrail screening and per-task rate limiting, then
 * consumed by the agent between turns (polling Query by task_id with
 * `consumed = false`). Unlike TaskEventsTable, this table has NO
 * DynamoDB stream — nudges are poll-consumed by the agent, not
 * fanned out to external channels.
 *
 * Rate-limit rows share the table with synthetic keys
 * (`task_id = 'RATE#<task>'`, `nudge_id = 'MINUTE#<yyyymmddhhmm>'`)
 * and carry a short TTL (~120s) so they are cleaned up automatically.
 */
export class TaskNudgesTable extends Construct {
  /**
   * The underlying DynamoDB table. Use this to grant access or read the table name.
   */
  public readonly table: dynamodb.Table;

  constructor(scope: Construct, id: string, props: TaskNudgesTableProps = {}) {
    super(scope, id);

    this.table = new dynamodb.Table(this, 'Table', {
      tableName: props.tableName,
      partitionKey: {
        name: 'task_id',
        type: dynamodb.AttributeType.STRING,
      },
      sortKey: {
        name: 'nudge_id',
        type: dynamodb.AttributeType.STRING,
      },
      billingMode: dynamodb.BillingMode.PAY_PER_REQUEST,
      timeToLiveAttribute: 'ttl',
      pointInTimeRecoverySpecification: {
        pointInTimeRecoveryEnabled: props.pointInTimeRecovery ?? true,
      },
      // No DynamoDB stream — nudges are poll-consumed by the agent runtime,
      // not fanned out to external channels like TaskEventsTable.
      removalPolicy: props.removalPolicy ?? RemovalPolicy.DESTROY,
    });
  }
}
